### ISSUE TITLE
Install and run in linux

### ISSUE THREAD

**Issue by tristanstoeber** [Daekkyn/brickr#2]
Hey,
I would love to use brickr on my ubuntu machine.
Would it be possible to get a minimal example on how to install and run it?
best,
tristan

**Comment by Daekkyn** [comment]
Hi,
I unfortunately have no experience on linux so I cannot help you.
Best,
Romain

**Comment by Ashwani1992** [comment]
Hi,
I tried running software on mac and getting following error "The file could not be voxelized with binvox. The format is probably not correctly handled by binvox or the software does not have administrative rights."

This is in AssemblyWidget.cpp file -> line 638

I am running it on mac os high sierra.

Please help how to resolved this.

Tried running .DMG file and still getting the same error.
