### ISSUE TITLE
Mac "voxelized with binvox" Error

### ISSUE THREAD

**Issue by Ashwani1992** [Daekkyn/brickr#3]
Hi,
I tried running software on mac and getting following error "The file could not be voxelized with binvox. The format is probably not correctly handled by binvox or the software does not have administrative rights."

This is in AssemblyWidget.cpp file -> line 638

I am running it on mac os high sierra.

Please help how to resolved this.

Tried running .DMG file and still getting the same error.

**Comment by Daekkyn** [comment]
Hi, 
Did you install XQuartz?
Otherwise you can try running Binvox separately: http://www.patrickmin.com/binvox/

**Comment by Ashwani1992** [comment]
Hi,

Yes, I installed XQuartz, but its still not work.

Alternatively, I have generated the .binvox file using the windows system and exported to the mac system and it worked.

Any suggestions please.

Thanks and Regards,
Ashwani

**Comment by Daekkyn** [comment]
Are you able to run Binvox on mac? If not, the problem is coming from Binvox and it would be better to ask Patrick Min directly.

**Comment by Ashwani1992** [comment]
Thanks :)

I will contact him.

Did you used the same logic/code (created by Patrick Min) in this?

Regards,
Ashwani

**Comment by Daekkyn** [comment]
No, he doesn't have a library to use his code so I had to directly call the binary. It's very hacky and should be replaced with a voxelization library.

**Comment by Ashwani1992** [comment]
Thanks for the timely help :)

I will check this with him.

Ashwani
