### ISSUE TITLE
How compile OpenMesh and Dolphin?

### ISSUE THREAD

**Issue by zhimaijoy** [Daekkyn/brickr#4]
Hi,
I have run it in windows. I read the code and find the AssemblyPlugin::loadTexture function. But it is it is commented out. 
I try to compile it, but OpenMeshNode and Dolphin are undeclared identifier. 
Please help me what are they. I could not find it.
Expecting a reply, Thank you !

**Comment by Daekkyn** [comment]
Hi, 
The texture library doesn't exist anymore so this functionality has to be recoded from scratch.

**Comment by zhimaijoy** [comment]
Hi，
Thanks for the timely help :)
I am  sad to hear the news. 

Regards,
zhimaijoy
