### ISSUE TITLE
Construction issue

### ISSUE THREAD

**Issue by clebail** [Daekkyn/brickr#5]
Hello,

I created a pretty big model, about 5300 bricks on 78 layers.
The statue is great, but the editing was not really easy, especially in the end, where you have to close the statue, it took me 2 hours to climb the last 2 layers of only 10 pieces ...

I thought that if the walls were wider, it would be easier. What do you think ? Can you tell me which places of the algoritme I can modify to test?

Thank you

**Comment by Daekkyn** [comment]
Hi,
You can define the wall thickness through the GUI with _Shell Thickness_. The default parameter is 2, but you can set 3 or 4 as needed.
