### ISSUE TITLE
Using more brick types for higher fidelity

### ISSUE THREAD

**Issue by chambm** [Daekkyn/brickr#6]
How hard would it be to modify the algorithm to use a much broader variety of Lego pieces? E.g. including curves, tiles, wheels, slopes, cylinders, windows, doors? Would it just be an extension of the current algorithm, or are these non-blocky pieces incompatible with the voxelization? I imagine using Technic pieces and modeling moving parts would be a totally different ballgame, but it'd be really cool to do that too. I'm basically wondering if algorithms like this can or will replace human master builders. :) Give the program a 3d model of something you want to build at minifig scale (which is generally too small for plain bricks to model with respectable detail), and voila!

**Comment by Daekkyn** [comment]
I feel this would be a very complicated problem to solve for an algorithm as you need to choose the pieces such that the end results "looks nice". This voxel based algorithm is in any case not suited for that.

**Comment by chambm** [comment]
Perhaps using this algorithm as a base for getting the internal structure would be a good place to start? Then some kind of optimization algorithm on top of that to maximize the fit to the model. Would that be a lot less computational work (and use fewer small pieces) than trying to optimize it from the full set of parts from scratch?

**Comment by chambm** [comment]
Now I'm thinking that the best way would be to optimize the shell first using the detail pieces (without any regard for support), then solve the inside afterward. The shell would put constraints on the inner shape, which I think your voxel algorithm could be used to solve.
